apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
