image:
  repository: ghcr.io/elizaaugusta4/distributed-tracing-python-kubernetes/cart
  tag: 438bbceee165623b3616c70fc617e4faa867da84
  pullPolicy: IfNotPresent
replicaCount: 3
service:
  port: 5001
serviceAccount:
  create: true
  name: ""
podSecurityContext:
  fsGroup: 10001
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5
  startup:
    path: /healthz
    periodSeconds: 5
    failureThreshold: 30
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
pdb:
  enabled: true
  minAvailable: 1
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: cart
          topologyKey: "kubernetes.io/hostname"
monitoring:
  enabled: true
  releaseLabel: kube-prometheus-stack
  path: /metrics
  interval: 15s
  scrapeTimeout: 10s
