blank_issues_enabled: false
contact_links:
  - name: Dúvidas / Discussão
    url: https://github.com/ElizaAugusta4/distributed-tracing-python-kubernetes/discussions
    about: Use Discussions para perguntas e ideias soltas.
