apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /tmp/tempo

      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: tempo-data
          emptyDir: {}
