apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tempo
  ports:
    - name: otlp
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: tempo-query
      protocol: TCP
      port: 3200
      targetPort: 3200