apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Release.Namespace }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    {{- if .Values.config.positions }}
    positions:
{{ toYaml .Values.config.positions | nindent 6 }}
    {{- else }}
    positions:
      filename: /tmp/positions.yaml
    {{- end }}
    {{- if .Values.config.clients }}
    clients:
{{ toYaml .Values.config.clients | nindent 6 }}
    {{- else if .Values.config.lokiAddress }}
    clients:
      - url: {{ .Values.config.lokiAddress | quote }}
    {{- else }}
    clients: []
    {{- end }}
    {{- if and .Values.config.snippets .Values.config.snippets.scrapeConfigs }}
    scrape_configs:
{{ .Values.config.snippets.scrapeConfigs | nindent 6 }}
    {{- else }}
    scrape_configs: []
    {{- end }}
