apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    app: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: {{ .Values.config.lokiAddress }}
    scrape_configs:
      - job_name: kubernetes-containers
        static_configs:
          - targets: ['localhost']
            labels:
              job: kubernetes-containers
              __path__: /var/log/containers/*.log
        pipeline_stages:
          - regex:
              expression: 'trace_id=(?P<trace_id>[a-f0-9]{32})'
          - labels:
              trace_id:
