apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      tolerations:                        # ← garante rodar em todos os nós
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: promtail
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: positions
              mountPath: /tmp
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
          resources: {}
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: positions
          hostPath:                       # ← no DaemonSet positions fica no nó
            path: /tmp/promtail-positions
        - name: varlogpods
          hostPath:
            path: /var/log/pods
