apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
      volumes:
        - name: config
          configMap:
            name: promtail-config
