apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/ElizaAugusta4/distributed-tracing-python-kubernetes
    targetRevision: HEAD
    path: charts/cart
    helm:
      parameters:
        - name: dependencyCheckUrls
          value: "http://catalog:5000/healthz"
  destination:
    server: https://kubernetes.default.svc
    namespace: virtual-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
