{
 "title": "Incidente – Erros, Logs e Traces",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Serviço",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Erros 5xx por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({service=~\"$service\", status_code=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs de Erro",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=~\"$service\", status_code=~\"5..\"}"
    }
   ]
  },
  {
   "title": "Traces com Erro",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "b77c52cd", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{\r\n  resource.service.name =~ \"$service\"\r\n  && span.http.status_code >= 500\r\n  && span.http.status_code < 600\r\n}",
     "tableType": "traces"
    }
   ]
  }
 ]
}