apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.observability:4318/v1/traces"
