apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
