{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Chart.Name .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: catalog
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
